#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login_check:
  path: /login_check
  methods: [POST]

api_login_check:
  path: /api/login_check

addingGroupe:
  path: /api/admin/groupes
  controller: App\Controller\GroupeController::addGroupes

putingGroupe:
  path: /api/admin/groupes/{id}
  controller: App\Controller\GroupeController::putGroupes

deletingApprenantGroupe:
  path: /api/admin/groupes/{idA}/apprenant/{idB}
  controller: App\Controller\GroupeController::retireApprenantGroupe

AddingChat:
  path: /api/users/promo/{id}/apprenant/{id1}/chat
  controller: App\Controller\ChatController::AddNewChat

gettingChat:
    path: /api/users/promo/{id}/apprenant/{id1}/chat/date
    controller: App\Controller\ChatController::gettingChat

gettingBrief:
    path: /api/formateurs/promo/{promo}/groupe/{id}/briefs
    controller: App\Controller\BriefController::getBrief

recuperer_stat_referentiel:
  path: /api/formateurs/promo/{id}/referentiel/{num}/statistiques/competences
  controller: App\Controller\LivrablePartielController::RecupApprenantRef


