#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login_check:
  path: /login_check
  methods: [POST]

api_login_check:
  path: /api/login_check

addingGroupe:
  path: /api/admin/groupes
  controller: App\Controller\GroupeController::addGroupes

putingGroupe:
  path: /api/admin/groupes/{id}
  controller: App\Controller\GroupeController::putGroupes

deletingApprenantGroupe:
  path: /api/admin/groupes/{idA}/apprenant/{idB}
  controller: App\Controller\GroupeController::retireApprenantGroupe


